# Generated by Django 4.2.7 on 2026-03-04 11:59

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Host's full name", max_length=255)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('property_name', models.CharField(help_text='Name or description of the property', max_length=255)),
                ('city', models.CharField(help_text='City where the property is located', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Application status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Application submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update date')),
            ],
            options={
                'verbose_name': 'Host Application',
                'verbose_name_plural': 'Host Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='legal_hosta_email_9fd970_idx'), models.Index(fields=['status'], name='legal_hosta_status_a5331d_idx'), models.Index(fields=['-created_at'], name='legal_hosta_created_6c1855_idx')],
            },
        ),
    ]
