# Generated by Django 5.2.10 on 2026-02-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_property_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='has_ac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
