# Generated by Django 5.2.10 on 2026-03-04 11:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_update_propertyimage_and_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='propertyimage',
            new_name='properties__propert_94c164_idx',
            old_name='properties_property_id_order_idx',
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, help_text='Full street address of the property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='airbnb_ical_url',
            field=models.URLField(blank=True, help_text='Airbnb iCalendar sync URL for availability', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.PositiveIntegerField(default=1, help_text='Number of bathrooms', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.PositiveIntegerField(default=1, help_text='Number of bedrooms', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='booking_ical_url',
            field=models.URLField(blank=True, help_text='Booking.com iCalendar sync URL for availability', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Meknes', help_text='City where property is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the property', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_ac',
            field=models.BooleanField(default=True, help_text='Does property have air conditioning?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_pool',
            field=models.BooleanField(default=False, help_text='Does property have a swimming pool?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_wifi',
            field=models.BooleanField(default=True, help_text='Does property have WiFi?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary property image (auto-synced to S3 if configured)', null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(help_text="Property name (e.g., 'Luxury Beachfront Villa')", max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Nightly rate in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(help_text='Property this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', '-created_at'], name='properties__owner_i_282fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties__city_74fa1a_idx'),
        ),
    ]
