# Generated by Django 5.2.10 on 2026-02-03 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('booking', 'Booking')], max_length=20)),
                ('uid', models.CharField(help_text='Unique booking identifier from external calendar', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
